// Deterministic file writer. The whole review workflow is `git diff`, so two runs over
// identical sheet data must produce byte-identical output: no timestamps, no run counters,
// key order fixed by transform.mjs's toOrderedContent (not sheet row order), LF line
// endings, exactly one trailing newline, and a write is skipped entirely when the bytes
// on disk already match.

import { readFile, writeFile, mkdir } from "node:fs/promises";
import { dirname } from "node:path";

function normalizeLineEndings(value) {
    return value.replace(/\r\n/g, "\n");
}

export function renderContentModule(sheetTab, contentByLocale) {
    const body = JSON.stringify(contentByLocale, null, 2);
    const text =
        `// AUTO-GENERATED by \`npm run sync:guides\`. Do not edit by hand.\n` +
        `// Source: Google Sheet tab "${sheetTab}"\n` +
        `import type { GuideContentByLocale } from "../types";\n` +
        `\n` +
        `const content: GuideContentByLocale = ${body};\n` +
        `\n` +
        `export default content;\n`;
    return normalizeLineEndings(text);
}

/** @returns {"written"|"unchanged"} */
export async function writeIfChanged(filePath, text, { dryRun = false } = {}) {
    let existing = null;
    try {
        existing = normalizeLineEndings(await readFile(filePath, "utf8"));
    } catch (err) {
        if (err.code !== "ENOENT") throw err;
    }

    if (existing === text) return "unchanged";
    if (!dryRun) {
        await mkdir(dirname(filePath), { recursive: true });
        await writeFile(filePath, text, "utf8");
    }
    return "written";
}
